---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Create host
      host:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          type: "{{ host_type }}"
          name: "{{ host_name }}"
      register: result1
    - debug: var=result1['output']