---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Delete iscsiPortal
      iscsiPortal:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ iscsiPortal_id }}"
      register: result1
    - debug: var=result1['output']
