---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Create lun
      lun:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        createLun:
          name: "{{ lun_name }}"
          lunParameters: {pool: {id: "{{ pool_id }}"}, "size": "{{ lun_size }}"}
      register: result1
    - debug: var=result1['output']
