---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Modify nasServer
      nasServer:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modify:
          id: "{{ nasServer_id }}"
          name: "modifyNameByPlaybook"
      register: result1
    - debug: var=result1['output']