---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Get nfsShare id
      commonGetPost:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: nfsShare
          fields: id, filesystem 
      register: result
    - debug: var=result['output']['get'][0]['id']

    - name: Get storageResource id
      commonGetPost:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: filesystem
          id: "{{ result['output']['get'][0]['filesystem']['id'] }}"
          fields: storageResource
      register: result1
    - debug: var=result1['output']['get']['storageResource']['id']
    #['storageResource']['id']

    - name: Modify nfsShare
      nfsShare:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modify:
          storageResource: {'id': "{{ result1['output']['get']['storageResource']['id'] }}"}
          nfsShare: {'id': "{{ result['output']['get'][0]['id'] }}" }
          description: 'nfsShareModifiedPlaybook'
      register: result2
    - debug: var=result2['output']