---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Get nasServer id
      nasServer:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          fields: id
      register: result1
    - debug: var=result1['output']['get'][0]['id']

    - name: Create nfsServer
      nfsServer:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          nasServer: {'id': "{{ result1['output']['get'][0]['id'] }}"}
      register: result2
    - debug: var=result2['output']
