---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Create pool
      pool:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        createVSA:
          name: "{{ pool_name }}"
          addPoolUnitParameters: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}]

      register: result1
    - debug: var=result1['output']
